(define (repeat n l)
  (if (not (= n 5000)) (begin (l) (repeat (+ n 1) l))))
(define flip
  (let ((state 0))
    (lambda ()
      (if (= state 0)
          (set! state 1)
          (set! state 0))
      state)))
(repeat 0 (lambda ()
(and (= (flip) 1)
     (= (flip) 0)
     (= (flip) 1)
     (= (flip) 0))))